// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozoncigjsujogtyzfykf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96b25jaWdqc3Vqb2d0eXpmeWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTU2MDgsImV4cCI6MjA2NDk5MTYwOH0.mVGUGsDFfzMGk3liK6nsOjL_3IjZwuOlkgnGzeR0c-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);